apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
    name: tt-instrumentation
spec:
  exporter:
    endpoint: http://otelcol-opentelemetry-collector.obs.svc.cluster.local:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: always_on
